### ISSUE TITLE
Add a Section for Team on Homepage

### ISSUE THREAD

**Issue by piyushchauhan** [VatsalSin/TedxIITPatna#48]

**Comment by atm1504** [comment]
Team page already exists. It has been commented out. We need to change the Datas

**Comment by piyushchauhan** [comment]
https://drive.google.com/file/d/1ELXwUSSFcAg38GCP1VCDB5MT5AOSJGam/view?usp=sharing
Full Committee

https://drive.google.com/file/d/1LogC3RdRuKtu54cyX77KFhi40DusfTvh/view?usp=sharing 
Finance and Sponsorship

https://drive.google.com/file/d/1EQz_FoCFu9TUGhMheDcwBY7h-LHFbVTm/view?usp=sharing
Design and Web

https://drive.google.com/file/d/1VCELVmwcQRoEl-yMdVZDrD0dXgPEjaUI/view?usp=sharing
Hospitality

https://drive.google.com/file/d/1oSMnAIp31kbGMRxL4moKE7SgE9ixuPfm/view?usp=sharing
Advertising and Promotion

https://drive.google.com/file/d/1MgNOy9NOibhUlBBhqlRTMyM-x6aatW_y/view?usp=sharing
Management

https://drive.google.com/file/d/17JPrvpPVbDQaGr3GrdH6gOKS0QCoCx5s/view?usp=sharing
Planning
