### ISSUE TITLE
Fix Sponsors page in Chrome

### ISSUE THREAD

**Issue by piyushchauhan** [VatsalSin/TedxIITPatna#49]

**Comment by pranaykgupta** [comment]
![Screenshot (45)](https://user-images.githubusercontent.com/43784050/57466327-04a78f00-729e-11e9-955d-ff68c09c65e2.png)
![Screenshot (46)](https://user-images.githubusercontent.com/43784050/57466329-05402580-729e-11e9-9557-fef9254ecd3a.png)
What is the problem in sponsors page in chrome

**Comment by piyushchauhan** [comment]
In chrome it is not viewed properly
