### ISSUE TITLE
Remove maps from all pages except Homepage

### ISSUE THREAD

**Issue by piyushchauhan** [VatsalSin/TedxIITPatna#62]

**Comment by piyushchauhan** [comment]
- [ ] Remove maps from all pages except Homepage
- [ ] Only keep a small portion of the map on the homepage

**Comment by piyushchauhan** [comment]
@pranaykgupta  Please do this also

**Comment by pranaykgupta** [comment]
@piyushchauhan can you please describe small portion of map

**Comment by piyushchauhan** [comment]
Leave it as it is on the home page.
