### ISSUE TITLE
Add Professor In-Charge in team page

### ISSUE THREAD

**Issue by piyushchauhan** [VatsalSin/TedxIITPatna#64]
Add Dr. Rajendra N. Paramanik https://drive.google.com/file/d/1EuQlCC2bC61AQEE03Jy_jIBxQecDLDEt/view?usp=drivesdk in the first row of team page. So finally the first row will have
Professor In-Charge  |  Organiser  |  Co-Organiser

**Comment by piyushchauhan** [comment]
@pranaykgupta Please complete it when you get time.

**Comment by pranaykgupta** [comment]
@piyushchauhan done
